### PR TITLE
Deprecate the configmap configurations of the java injector.

### PR DESCRIPTION
**Pull request by dashanji**
Fixes https://github.com/apache/skywalking/issues/10931

### CODE REVIEW

**Comment by hanahmily** [comment]
@dashanji We updated OAP. Please fix the conflicts then we will release 0.8.0 once this get merged.

**Review by hanahmily — APPROVED** [review]

**Comment by hanahmily** [comment]
@dashanji Would you check out the "internal storage" case in e2e. I rerun it several times, there must be some issues in it.

**Comment by wu-sheng** [comment]
And are the OAP, UI, and database upgraded to latedt by default?

**Comment by dashanji** [comment]
@hanahmily, @wu-sheng. The e2e test can run successfully on my local machine, and I want to debug it on the CI. 

But It looks like we can't add the tmate action as https://github.com/apache/skywalking-swck/actions/runs/5628640535, do you have any idea?

**Comment by wu-sheng** [comment]
@kezhenxu94 any thought?

**Comment by kezhenxu94** [comment]
> @hanahmily, @wu-sheng. The e2e test can run successfully on my local machine, and I want to debug it on the CI.
> 
> But It looks like we can't add the tmate action as https://github.com/apache/skywalking-swck/actions/runs/5628640535, do you have any idea?

Don’t over use those tools, collect logs and look into the logs first. It’s time/resource consuming to use that tool to log into the CI machine. now the CI failed and the logs show Pod is not ready in time. next is to collect the pod logs and see whether there is error in it, this is not only useful for this time but also for future

**Comment by kezhenxu94** [comment]
FYI about how to collect logs https://github.com/apache/skywalking/blob/e0068154c1253500720651dca5c80c3ae10ca87b/.github/workflows/skywalking.yaml#L687

**Comment by dashanji** [comment]
> FYI about how to collect logs https://github.com/apache/skywalking/blob/e0068154c1253500720651dca5c80c3ae10ca87b/.github/workflows/skywalking.yaml#L687

Make sense to me. Thanks a lot!

**Review by hanahmily — APPROVED** [review]

**Pull request merged**
