### PR TITLE
use JAVA_TOOL_OPTIONS to replace AGENT_OPTS

### PR DESCRIPTION
**Pull request by dashanji**
Signed-off-by: dashanji <952129620@qq.com>

### CODE REVIEW

**Comment by wu-sheng** [comment]
@hanahmily Please confirm whether we still accept PR in 0.6.0 release RC

**Comment by wu-sheng** [comment]
Could you explain or provide some references about differences between `JAVA_TOOL_OPTIONS` and `AGENT_OPTS`

**Comment by dashanji** [comment]
@wu-sheng yep, I think the difference is [here](https://github.com/apache/skywalking-showcase/pull/14#discussion_r775429367).

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
Make sense to me. Wait for release manager's confirmation.

**Review by hanahmily — APPROVED** [review]
LGTM

**Pull request merged**
