### PR TITLE
Support inject java agent bootstrap-plugins.

### PR DESCRIPTION
**Pull request by weixiang1862**
For https://github.com/apache/skywalking/discussions/11276

### CODE REVIEW

**Comment by dashanji** [comment]
@weixiang1862 Thanks for the quick pr, could you please add an e2e test to validate the bootstrap plugins are moved into the plugins?

**Comment by weixiang1862** [comment]
> @weixiang1862 Thanks for the quick pr, could you please add an e2e test to validate the bootstrap plugins are moved into the plugins?

OK, I will add a case.

**Comment by weixiang1862** [comment]
> @weixiang1862 Thanks for the quick pr, could you please add an e2e test to validate the bootstrap plugins are moved into the plugins?

Added.

**Comment by weixiang1862** [comment]
seems it is a high frequency error when run e2e, the operator not really `ready`:
```
Error from server (InternalError): error when creating "test/e2e/skywalking-components-with-swagent-configmap.yaml": Internal error occurred: failed calling webhook "mswagent.kb.io": Post "[https://skywalking-swck-webhook-service.skywalking-swck-system.svc:443/mutate-operator-skywalking-apache-org-v1alpha1-swagent?timeout=10s](https://skywalking-swck-webhook-service.skywalking-swck-system.svc/mutate-operator-skywalking-apache-org-v1alpha1-swagent?timeout=10s)": context deadline exceeded
```

**Comment by dashanji** [comment]
> seems it is a high frequency error when run e2e, the operator not really `ready`:
> 
> ```
> Error from server (InternalError): error when creating "test/e2e/skywalking-components-with-swagent-configmap.yaml": Internal error occurred: failed calling webhook "mswagent.kb.io": Post "[https://skywalking-swck-webhook-service.skywalking-swck-system.svc:443/mutate-operator-skywalking-apache-org-v1alpha1-swagent?timeout=10s](https://skywalking-swck-webhook-service.skywalking-swck-system.svc/mutate-operator-skywalking-apache-org-v1alpha1-swagent?timeout=10s)": context deadline exceeded
> ```

I think you'd better to test the case locally.

**Comment by weixiang1862** [comment]
@wu-sheng @dashanji Could you please re-run the failed cases? They all passed on my local.

**Comment by wu-sheng** [comment]
@dashanji Could you check the CI whether it is unstable?

**Comment by dashanji** [comment]
> @dashanji Could you check the CI whether it is unstable?

From my experience, it's mainly caused by the resource limitation of the CI machine. we can free the unnecessary libraries to make resources for the e2e test.

**Review by dashanji — APPROVED** [review]

**Pull request merged**
